package org.filmt.projetagile.posts.service.impl;

import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import org.filmt.projetagile.groups.service.impl.GroupServiceMock;
import org.filmt.projetagile.posts.model.Post;
import org.filmt.projetagile.posts.service.PostService;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class PostServiceMock implements PostService {

    public static List<String> UUIDS = List.of("d389b9cc-e94e-4b45-a1f3-4231a3be00e4",
            "ff5c5310-76e8-4901-87fc-1e45d50f91a1",
            "d6461113-bd73-4028-9d1c-682f93647f1c",
            "39e2cecf-b4e4-4dde-bd47-3f5ae7822785",
            "fdfc779d-485d-45a4-9ab0-1f2e70a68397",
            "5d86be5a-d618-4737-95d3-4ac4d41ee1ad",
            "aecddcbd-0a99-4e3e-b455-b8c98c960042",
            "06d9d5f2-3520-49f8-a51e-a6c881852a1f",
            "73d5ffc0-5326-4a29-8f34-9d8bdb8d7566",
            "24686629-0cee-4533-a2ee-0f39462c6801",
            "f237f0fc-55f2-469b-a5a1-1cdb4ddd167d",
            "eef9255e-eeaf-40af-8729-3767f04ff339",
            "077d4313-ea11-497d-9539-4ac839663add",
            "25fd6d91-0948-4d1e-ab34-707eddd41b62",
            "85b292d0-1d85-4b96-a47a-71d8c77c9ee2",
            "d941a5a9-bbf6-44ac-85d9-a7cd005349f7",
            "d007ecda-df5a-4952-a06a-2e11d3e4de05",
            "5c9ad24a-b759-4c89-9d88-13be9a8c10c4",
            "1b89d0d3-d33c-416b-8900-9589b9118d21",
            "b41be9b7-6ef3-44c6-9ca9-06d6f73ff964",
            "d43446e1-849f-40af-ae02-f7d4e1b4b7e2",
            "5e1a1e27-1937-4a2e-ac2e-9e53590827c5",
            "880fe7a7-5368-4050-8d95-583d71ffb928",
            "c6db6f3c-2464-4324-a4d8-967f53aedbb6",
            "d54dd285-9e9e-490e-a902-181b9cf586c4",
            "0ab61616-28a4-450a-87ea-8c5168228fd7",
            "8f5bf0cc-663f-4c64-b3d3-059dbc6b2c5f",
            "aa193d61-5390-42be-9d2f-eb20565ba970",
            "8455b547-c8fb-436e-8a07-9dfb78b7117c",
            "0b22076f-edb4-4a6d-9157-f1d58493f1e2",
            "2380a0ba-7f1e-4c52-8797-1543a27bd463",
            "a3c66536-77ad-418c-a784-9cf0eb5b3f10",
            "5166e5b4-83b0-4535-93ed-6d4a804058d9",
            "26b92b21-8239-44ef-9bf1-bca4e0c23308",
            "12c26550-1dbd-41ff-9ea8-27326be89e22",
            "7ade3e5f-a333-4b55-b9be-d24fcb7a4b02",
            "c4089ee9-11bd-490e-960e-238eea87c096",
            "5b1e4c1a-1d3a-4b43-893f-79b245381e24",
            "8f795f07-01a4-4022-966c-a92a5d4a5ac2",
            "a52a6232-25a4-4b25-be28-6d494e6d0d31",
            "c9116465-3b1c-4669-8d73-dde4c4cc61f6",
            "d39c6796-2789-4b8e-a87e-2db8097fc7e3",
            "9ddfa324-2a86-47e1-8dbc-09fe95eb58fb",
            "8c4dfb28-0599-4ead-af94-7d9b004439df",
            "927248e3-7105-4850-bf95-30c008b30787",
            "46ab9a0f-53b2-4f46-aff4-db082e986f5a",
            "4b8ab8e5-94e2-4662-90a3-d8d291d89a66",
            "46113e4f-fbc0-40c2-9b82-3a104f4350a9",
            "119eee66-eec6-4d54-98df-dd1045537a90",
            "a81a19d9-254a-41c2-bc14-dfb960f2de17");

    @Override
    public List<Post> getPostsByGroupId(String groupId) {
        return List.of(
                new Post(UUIDS.get(1 - 1), GroupServiceMock.UUIDS.get(1 - 1), "Bean homes presented dream threatened champions now, contacts cardiac breath tank lewis cape real, accounting removing sit boundary defense lp suzuki, presence thumbnails gave prerequisite peripheral. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(2 - 1), GroupServiceMock.UUIDS.get(2 - 1), "Package resume resolved hearings stamps disks bind, effectiveness feeds upload fewer brilliant banana horn, instrumentation minutes wax jeffrey reliance blowing concerning, adaptation italy everybody initiatives contributors. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(3 - 1), GroupServiceMock.UUIDS.get(3 - 1), "Suzuki flash petersburg fighters neighborhood fold marathon, entrepreneur assuming chocolate muscle console. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(4 - 1), GroupServiceMock.UUIDS.get(4 - 1), "Quick receptor she latinas southampton generous checkout. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(5 - 1), GroupServiceMock.UUIDS.get(5 - 1), "Sheriff buttons diploma nova belts sugar threshold, postings extend individuals avi nowhere alien celebrity, torture preservation comics experts spring believed carlo, manuals rosa. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(6 - 1), GroupServiceMock.UUIDS.get(6 - 1), "Straight dame cyprus jeep rica brush newfoundland, eden paypal optimization apparel effects alaska bible, powerseller bed entry excitement suite dev. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(7 - 1), GroupServiceMock.UUIDS.get(7 - 1), "Admitted couples capture mart grove anymore incomplete, cheaper advice spice electronics malta southeast savannah, ruth larry survivor donate guilty eddie wallet, ripe influenced corps turkish extend. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(8 - 1), GroupServiceMock.UUIDS.get(8 - 1), "Fountain judicial lip app evaluated advisor beach, sought jose rental crystal intervals orange israeli, profits fur bailey muslim submitted discussion gas, communities graphic traffic landscapes drink constitute ads, zoning. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(9 - 1), GroupServiceMock.UUIDS.get(9 - 1), "Index monitor labor hull list medications question, naples limited inputs besides change rss advisor, allow webcast elimination train preparing sponsor fear, uploaded registrar. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(10 - 1), GroupServiceMock.UUIDS.get(10 - 1), "Begin monaco limit former. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(11 - 1), GroupServiceMock.UUIDS.get(11 - 1), "Preview enlarge queens freight doom cordless disputes, glad personnel era fit lamp wheat motion, firms blonde holy tim lindsay. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(12 - 1), GroupServiceMock.UUIDS.get(12 - 1), "Response bug began animated oven ashley utility, reservation teenage drawings admitted closer secretary. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(13 - 1), GroupServiceMock.UUIDS.get(13 - 1), "Adopted bestsellers combination salem offered equipment wired, there exposure fold chassis theories overcome see, harmony intro race measure bras cyber products, recognition. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(14 - 1), GroupServiceMock.UUIDS.get(14 - 1), "Rescue hobbies strict proteins title argued peripheral, inventory capable chaos ok morning. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(15 - 1), GroupServiceMock.UUIDS.get(15 - 1), "Nearest ceremony failed christopher morning proceedings dover, likelihood strengthening reputation munich color french honduras, thursday robertson. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(16 - 1), GroupServiceMock.UUIDS.get(16 - 1), "Cowboy tale welsh consumer links kathy beds, entertaining. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(17 - 1), GroupServiceMock.UUIDS.get(17 - 1), "Unauthorized appropriate opponents corp eleven consistency writings, block. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(18 - 1), GroupServiceMock.UUIDS.get(18 - 1), "Chains success logos oriental salmon earth blink, rain unauthorized istanbul webmaster happened supervision freeze, embedded computation sodium applicant cooling retail grocery, proved resources adelaide object swimming honest coated, classics. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(19 - 1), GroupServiceMock.UUIDS.get(19 - 1), "Doubt alaska pull oriental importance connector crack, wallpaper isaac pumps puzzles stuff reseller projects, sponsors parameter malpractice milan durable limitations terrain, doll tampa view evaluated entitled. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(20 - 1), GroupServiceMock.UUIDS.get(20 - 1), "Votes extras economies police medium hottest saw. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(21 - 1), GroupServiceMock.UUIDS.get(21 - 1), "Jets roulette reward outlined just confident plots, chile backup grammar mason heading topic poison, attached xhtml sisters financial combat keith intake, alice barn commissions. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(22 - 1), GroupServiceMock.UUIDS.get(22 - 1), "Testing fare its graduation organisation buffalo broken, efficiently posing brick rat resorts geology hate, lamb noon logan in details person engage, export trailers gale unfortunately patrick. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(23 - 1), GroupServiceMock.UUIDS.get(23 - 1), "Electoral barrier money uganda vehicle designer jeff, staffing consultation managed chemicals schools subsidiary climb, hundred. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(24 - 1), GroupServiceMock.UUIDS.get(24 - 1), "Declined christians sublime die tech apparent specified, securely instrumental yield personals rates cope scheduling, magical three patterns dispatched vision designation working, cooler ties jean. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(25 - 1), GroupServiceMock.UUIDS.get(25 - 1), "Yemen vocal kernel accused rachel tent teacher, really individual artificial happens monitors boots exempt, hill doubt beneficial rear took trees stuart. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(26 - 1), GroupServiceMock.UUIDS.get(26 - 1), "Ventures arbor effectively kind asylum ideas ancient, statutes promotion stakeholders mercury judy administrator dried, fioricet aquarium singh uzbekistan jane fundraising crowd, acute grades controller most. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(27 - 1), GroupServiceMock.UUIDS.get(27 - 1), "Spice walnut hist headers instruments wound previews, mentor trend cambodia oil lap generators effort, dress. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(28 - 1), GroupServiceMock.UUIDS.get(28 - 1), "Issues operating forever titanium betting regulations incorporate, respected mediawiki meals reviewer apollo consistently affect, grid continues concerned participant talking martin. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(29 - 1), GroupServiceMock.UUIDS.get(29 - 1), "Absolute seriously including city meanwhile promotion. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(30 - 1), GroupServiceMock.UUIDS.get(30 - 1), "Divine achieving donald fundamentals mailman wanted liquid, remind area converter dome privacy telecom penn, limited modes techno. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(31 - 1), GroupServiceMock.UUIDS.get(31 - 1), "Ok island infinite look victoria preferred chemical, planet wisdom kids it conviction notifications sizes, portal incredible stewart composer suitable political exam, sapphire miscellaneous egyptian exclusively. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(32 - 1), GroupServiceMock.UUIDS.get(32 - 1), "Christina dennis map palmer blessed corrections junction, line stability hitachi reducing sacrifice hiring modeling, premiere jeep. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(33 - 1), GroupServiceMock.UUIDS.get(33 - 1), "Leave concern independence syndicate browser steps bankruptcy, brief fabric fast discipline pit venice present, hebrew indicating that careers figure lunch although, variance nato const afternoon black orientation. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(34 - 1), GroupServiceMock.UUIDS.get(34 - 1), "Motivation volvo hip why. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(35 - 1), GroupServiceMock.UUIDS.get(35 - 1), "Installed avenue pumps excel uploaded conscious porsche, teach longest mini rice marvel affiliates restricted, lower obligations wrote adding pontiac introduced evanescence, gourmet verification listings islands. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(36 - 1), GroupServiceMock.UUIDS.get(36 - 1), "Rover workforce cut contributions mini spreading. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(37 - 1), GroupServiceMock.UUIDS.get(37 - 1), "Referral domain king patio appliances stickers surprised, marilyn alive complement doctrine requests wallet. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(38 - 1), GroupServiceMock.UUIDS.get(38 - 1), "Mountain forbidden hebrew furnished northwest sure. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(39 - 1), GroupServiceMock.UUIDS.get(39 - 1), "Severe liverpool rounds army martin fine beef, religions expand boot basement mineral bras venue, chester lane movements firm salvador noble white, journals cord generator chain theft fabrics snake. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(40 - 1), GroupServiceMock.UUIDS.get(40 - 1), "Eugene leads pen pregnancy arrangements kentucky orchestra, photos violence spyware large petroleum lined registry, phones discharge. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(41 - 1), GroupServiceMock.UUIDS.get(41 - 1), "Bears monitor toolkit due amy containing shooting, yes puerto. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(42 - 1), GroupServiceMock.UUIDS.get(42 - 1), "Accreditation absolutely conducted putting hence seeking assure, batteries drove. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(43 - 1), GroupServiceMock.UUIDS.get(43 - 1), "Adjustment respond curriculum education pizza abilities words, knives seeking corners realize recommend utilization. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(44 - 1), GroupServiceMock.UUIDS.get(44 - 1), "Tiffany cork former ballot subscriber psychology argued. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(45 - 1), GroupServiceMock.UUIDS.get(45 - 1), "Dual terminology hanging weird exec mortgage mortality, cure spirituality. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(46 - 1), GroupServiceMock.UUIDS.get(46 - 1), "Litigation agents expression birmingham henry. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(47 - 1), GroupServiceMock.UUIDS.get(47 - 1), "Diagnostic stop colleagues scan shaped tea referring, total injury hung bikes soccer institutes launched, digital appearance global capture entrepreneur starter. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(48 - 1), GroupServiceMock.UUIDS.get(48 - 1), "Lanka breach theories writer internship. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(49 - 1), GroupServiceMock.UUIDS.get(49 - 1), "Mountain tulsa interpreted grace lawsuit alcohol spare, biz wage numeric relief restrictions prints framing, booking artists volt catalog rows. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(50 - 1), GroupServiceMock.UUIDS.get(50 - 1), "Lessons warner witch tracked worm sterling recall, stadium predict scott pics priced keno penn, junk. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."));
    }

    @Override
    public List<Post> getPostByCategory(String groupId, String categoryId) {

        return List.of(
                new Post(UUIDS.get(21 - 1), GroupServiceMock.UUIDS.get(21 - 1), "Jets roulette reward outlined just confident plots, chile backup grammar mason heading topic poison, attached xhtml sisters financial combat keith intake, alice barn commissions. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(22 - 1), GroupServiceMock.UUIDS.get(22 - 1), "Testing fare its graduation organisation buffalo broken, efficiently posing brick rat resorts geology hate, lamb noon logan in details person engage, export trailers gale unfortunately patrick. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(23 - 1), GroupServiceMock.UUIDS.get(23 - 1), "Electoral barrier money uganda vehicle designer jeff, staffing consultation managed chemicals schools subsidiary climb, hundred. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(24 - 1), GroupServiceMock.UUIDS.get(24 - 1), "Declined christians sublime die tech apparent specified, securely instrumental yield personals rates cope scheduling, magical three patterns dispatched vision designation working, cooler ties jean. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(25 - 1), GroupServiceMock.UUIDS.get(25 - 1), "Yemen vocal kernel accused rachel tent teacher, really individual artificial happens monitors boots exempt, hill doubt beneficial rear took trees stuart. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(26 - 1), GroupServiceMock.UUIDS.get(26 - 1), "Ventures arbor effectively kind asylum ideas ancient, statutes promotion stakeholders mercury judy administrator dried, fioricet aquarium singh uzbekistan jane fundraising crowd, acute grades controller most. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(27 - 1), GroupServiceMock.UUIDS.get(27 - 1), "Spice walnut hist headers instruments wound previews, mentor trend cambodia oil lap generators effort, dress. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(28 - 1), GroupServiceMock.UUIDS.get(28 - 1), "Issues operating forever titanium betting regulations incorporate, respected mediawiki meals reviewer apollo consistently affect, grid continues concerned participant talking martin. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(29 - 1), GroupServiceMock.UUIDS.get(29 - 1), "Absolute seriously including city meanwhile promotion. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(30 - 1), GroupServiceMock.UUIDS.get(30 - 1), "Divine achieving donald fundamentals mailman wanted liquid, remind area converter dome privacy telecom penn, limited modes techno. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(31 - 1), GroupServiceMock.UUIDS.get(31 - 1), "Ok island infinite look victoria preferred chemical, planet wisdom kids it conviction notifications sizes, portal incredible stewart composer suitable political exam, sapphire miscellaneous egyptian exclusively. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(32 - 1), GroupServiceMock.UUIDS.get(32 - 1), "Christina dennis map palmer blessed corrections junction, line stability hitachi reducing sacrifice hiring modeling, premiere jeep. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(33 - 1), GroupServiceMock.UUIDS.get(33 - 1), "Leave concern independence syndicate browser steps bankruptcy, brief fabric fast discipline pit venice present, hebrew indicating that careers figure lunch although, variance nato const afternoon black orientation. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(34 - 1), GroupServiceMock.UUIDS.get(34 - 1), "Motivation volvo hip why. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(35 - 1), GroupServiceMock.UUIDS.get(35 - 1), "Installed avenue pumps excel uploaded conscious porsche, teach longest mini rice marvel affiliates restricted, lower obligations wrote adding pontiac introduced evanescence, gourmet verification listings islands. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."),
                new Post(UUIDS.get(36 - 1), GroupServiceMock.UUIDS.get(36 - 1), "Rover workforce cut contributions mini spreading. ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."));
    }

    @Override
    public List<Post> getPostsBySchoolIdAndTitle(String schoolId, String title) {
        return null;
    }

    @Override
    public List<Post> getPostsByGroupIdAndTitle(String groupId, String title) {
        return null;
    }

    @Override
    public Post create(Post post) {
        return new Post();
    }

    @Override
    public Post update(Post post) {
        return null;
    }

    @Override
    public void delete(String id) {

    }
}
