@startuml
entity CATEGORY {
* ID_CATEGORY : number <<generated>>
* ID_GROUPE : number <<FK>>
--
* LIBELLE : text
}

entity POST {
  * ID : number <<generated>>
  * GROUPE_ID : number<<FK>>
  --
  * LIBELLE : text
  DESCRIPTION : text
}
entity CIR_CATEGORY_POST {
    * ID_GROUPE : number <<FK>>
    * ID_POST : number <<FK>>
}
entity GROUPE {
  * ID : number <<FK>>
  --
  * ID_ECOLE : number <<FK>>
  * LIBELLE : text
  DESCRIPTION : text
}

entity ECOLE {
  * ID : number <<FK>>
  --
  * LIBELLE : text
  DESCRIPTION : text
}

entity REPLY {
    * POST_ID : number<<FK>>
    * GROUP_ID : number<<FK>>
    * ID : number<<generated>>
    --
    * CONTENT : text
    ID_REPLY
}

entity LIKE_REPLY {
    * ID_USER
    * ID_REPLY
}

entity LIKE_POST {
    * ID_USER
    * ID_POST
}

entity TYPE_ECOLE {
* ID_TYPE : number <<generated>>
--
LIBELLE : text
}

entity UTILISATEUR {
* ID_UTILISATEUR
--
* PSEUDO
* PWD
AVATAR_URL
GLOBAL_ADMIN
NOTE_PERSO
}

entity ROLE {
* ID_ROLE
--
LIBELLE
}

entity ROLE_GROUPE {
    * ID : number <<FK>>
    * ID_UTILISATEUR : number <<FK>>
    --
    * ID_ROLE : number <<FK>>
}

TYPE_ECOLE |o-up-o{ ECOLE
CATEGORY }|-right-|| GROUPE
GROUPE ||-down-o{ POST
ECOLE ||-left-|{ GROUPE
POST ||--o{ REPLY
REPLY ||-right-o{ REPLY
CIR_CATEGORY_POST }|-up-|{ CATEGORY
CIR_CATEGORY_POST }|-right-|{ POST
GROUPE ||-up-|{ ROLE_GROUPE
UTILISATEUR }o-left-o{ ROLE_GROUPE
UTILISATEUR }o-down-|{ ECOLE
ROLE }|-right-o{ ROLE_GROUPE
UTILISATEUR }o--o{ LIKE_POST
UTILISATEUR }o--o{ LIKE_REPLY
POST }o--o{ LIKE_POST
REPLY }o--o{ LIKE_REPLY
@enduml